### ISSUE TITLE
Compatibility with MacOS Monterey 12.3 (Python removed)

### ISSUE THREAD

**Issue by damonsharp** [alexchantastic/alfred-lipsum-workflow#6]
Hi Alex -

Appreciate you putting this workflow together. I used it almost daily. Wondering if you've tested [this workaround](https://www.alfredapp.com/help/kb/python-2-monterey/) for Python being removed from Monterey. I can't seem to get this to work. Wondering if you have a workaround or know of a fix.

example...

https://user-images.githubusercontent.com/867556/158880056-423bec19-5029-43e9-a75f-c04196345021.mp4

**Comment by alexchantastic** [comment]
Thanks for bringing this to my attention! I've created a new release ([v3.2.0](https://github.com/alexchantastic/alfred-lipsum-workflow/releases/tag/v3.2.0)) that now requires Python 3 instead of Python 2.

I've added some instructions in the [README](https://github.com/alexchantastic/alfred-lipsum-workflow/tree/master#dependencies) on what this means and how to install Python 3 to get the workflow running again.

Unfortunately, it does require some steps due to Apple no longer bundling Python with macOS. I plan to address this more thoroughly with #7 in the future so that you won't need to install any dependencies at all.

Please let me know if you have any trouble getting the workflow running again and I can help troubleshoot.

**Comment by damonsharp** [comment]
@alexchantastic - Thanks so much for looking into this and providing a solution so quickly. I'll give this a run through some time this weekend and let you know.

**Comment by damonsharp** [comment]
@alexchantastic all good. working like a charm. thanks again!
