### ISSUE TITLE
Incorrect options provided

### ISSUE THREAD

**Issue by datagitateur** [alexchantastic/alfred-lipsum-workflow#8]
Hi, 
Newbie question and apologize for my english. I get an "incorrect options provided" when using last lipsum workflow .

My configuration :  
- Mac os 12.3 Monterey
- Lipsum-shell installed in my user directory and running well (see screenshot)
![lipsum-shell](https://user-images.githubusercontent.com/49562134/159222147-c5a38213-ddf9-4230-a1b8-82dbaa09364c.png)
- Alfred 4.6.3 with Power pack running

Lipsum workflow running, but i'm getting "incorrect options provided"

Thanks in advance ! 

Herveo

**Comment by alexchantastic** [comment]
No worries, your English is fine! 😃 

Can you provide a few more details? Which workflow action are you running with what values? Does it happen for all of them? I'm not able to reproduce the issue on my machine at the moment.

It would also be great to see the debugging output:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/604167/159311249-9444f767-e5bf-4801-90e5-c09b0c15808b.png">

Check out this [help article](https://www.alfredapp.com/help/workflows/advanced/debugger/) on how to access that screen.

You may want to try deleting the workflow and re-installing it as start if you haven't already. The error you seem to be getting has to do with not passing the correct parameters to `lipsum-shell`, but the workflow should handle all of this for you.

As a side note, you don't need to install `lipsum-shell` for the workflow to work since it comes bundled with it.

**Comment by datagitateur** [comment]
Thanks for your reply, 

The error occurs on all workflow. 
Use case : New textedit document, alfred shortcut , lipsum typing, sentence select and finally enter key
again, same error for the four workflows

here a screen copy with debug mode on 
<img width="1196" alt="Capture d’écran 2022-03-21 à 18 31 04" src="https://user-images.githubusercontent.com/49562134/159331168-e7c85e7e-b0fd-4c04-bea9-d4123a0f7afe.png">

I have already deleted the workflow, reboot , download and reinstall ... error still occurs 

Ok side note ... noted ;-) i will uninstall ipsum-shel as i use only your alfred workflow

Thanks in advance

Hervé

**Comment by alexchantastic** [comment]
Thanks for providing the extra context! 🙌 

I see the problem now. In order for the workflow to give you output, you have to specify the number of structures you want it to produce. For example, if you wanted to produce 25 sentences, you would write `lipsum 25` and then select sentences.

![image](https://user-images.githubusercontent.com/604167/159335369-62ae4539-994c-4739-8e57-db0184818344.png)

Unfortunately, I didn't build and defaults in with this new version so I should fix that. Another thing I can do is make the error handling on `lipsum-shell` a bit better so it doesn't spit out that error text if you don't enter in the correct parameters.

Let me know if that solves your issue.

**Comment by alexchantastic** [comment]
I just released [v4.0.1](https://github.com/alexchantastic/alfred-lipsum-workflow/releases/tag/v4.0.1) which now has the default value behavior again. Let me know if that fixes the issue for you!

**Comment by datagitateur** [comment]
Whaou ! great release 

- former behavior with pre defined params
- new behavior with the length choice

Thank you very much
